name: Caitlin
favicon: null
layout_spectrum: 0.3698378570843488
typography_spectrum: 0.2575936692301184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3343829051591456
  lightness: 0.9621642180718482
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
